name: CI - Tests avant déploiement

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Installer les dépendances
      run: |
        npm ci
        npm install --save-dev happy-dom @vitest/coverage-v8

    - name: Vérifier l'environnement
      run: |
        node --version
        npm --version
        npx vitest --version

    - name: Lancer les tests
      run: npm run test:ci
      env:
        CI: true
        NODE_ENV: test
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Générer le rapport de couverture
      run: npm run test:coverage
      env:
        CI: true
        NODE_ENV: test

    